version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "04:00"
  reviewers:
  - 7h1b0
  labels:
  - dependencies
  versioning-strategy: increase
