language: node_js
node_js:
  - 'node'

cache:
  npm: true
  directories:
    - ~/.cache

install:
  - npm ci

before_script:
  - npm run build

script:
  - npm run lint
  - npm run format:check
  - npm run coverage

notifications:
  email: false
