language: node_js
node_js:
  - 'node'

cache:
  directories:
    - '$HOME/.npm'

install:
  - npm ci

before_script:
  - npm run build
  - npm run serve &

script:
  - npm run lint
  - npm run prettier:check
  - npm run coverage

notifications:
  email: false
