language: node_js
node_js:
  - 'lts/*'

cache:
  directories:
    - '$HOME/.npm'

install:
  - npm ci

before_script:
  - npm run build
  - npm run serve:prod &

script:
  - npm run lint
  - npm run coverage

notifications:
  email: false
