language: node_js
node_js:
  - 'lts/*'

cache:
  directories:
    - '$HOME/.npm'

install:
  - npm ci

before_script:
  - npm start &

script:
  - npm run lint
  - npm run coverage
  - npm run build

notifications:
  email: false
