name: Node.js CI

on: [push]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Run svelte check
        run: npm run check

      - name: Run format check
        run: npm run format:check

      # - name: Run unit tests
      #   run: npm run test:coverage

      # - name: Upload coverage
      #   uses: codecov/codecov-action@v1
      #   with:
      #     flags: unittests
      #     file: ./coverage/clover.xml

  test:
    name: Cypress run
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: ['chrome', 'firefox']
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Run build script
        run: npm run build:coverage

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          browser: ${{ matrix.browser }}
          start: npm run preview
          wait-on: 'http://localhost:5000'

      - name: Upload coverage
        uses: codecov/codecov-action@v1
        with:
          flags: ${{ matrix.browser }}
          file: ./coverage/clover.xml
