name: Node.js CI

on: [push]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Run svelte check
        run: npm run check

      - name: Run format check
        run: npm run format:check

      - name: Run unit tests
        run: npm run test

  test:
    name: Cypress run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Run build script
        run: npm run build

      - name: Cypress run
        uses: cypress-io/github-action@v3
        with:
          browser: 'chrome'
          start: npm run preview -- --host
          wait-on: 'http://localhost:4173'

  release:
    if: ${{ contains('refs/heads/master', github.ref) }}
    needs: [validate, test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build
        run: npm run build -- --base=/todos

      - name: Release
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npx gh-pages -d dist -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
