name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm ci
      - run: npm run build
      - run: npm run lint:check
      - run: npm run format:check
      - name: unit tests
        run: npm run coverage
      - name: E2E tests
        uses: cypress-io/github-action@v2
        with:
          start: npx serve -s dist/ -l 3000 -n
          wait-on: 'http://localhost:3000'
